### ISSUE TITLE
Make waveform appearance consistent

### ISSUE THREAD

**Issue by thomasjonesmc** [thomasjonesmc/send-a-demo#48]
Currently waveform appearance differs based on how long the demo is. For short demos, waveforms are extremely spaced out. For long demos the waveforms are too close together. The waveforms should have a consistent appearance regardless of demo length.

**Comment by samstorment** [comment]
# Height Difference With and Without Waveform

Additionally for this issue, I think it might be nice to try to make the overall height of the track consistent with and without the presence of the waveform. When a track has a waveform, it grows to be a quite a bit taller. A track without a waveform is shorter, just tall enough to accommodate the height of the two buttons on the right side. I think it would be nice if a track with a waveform was the same height as the waveform-less track. 

This problem ties in nicely with the overall theme of this issue, so I added I left this comment here rather than creating a new issue. Below is a screenshot of the problem I described above.

![Screenshot 2021-02-12 045811](https://user-images.githubusercontent.com/57368524/107760155-ef6f5800-6cee-11eb-92c8-03443b77e6cf.png)
